apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  OAUTH2_PROXY_CLIENT_ID: {{ .Values.oidc.client_id | quote }}
  OAUTH2_PROXY_CLIENT_SECRET: {{ .Values.oidc.client_secret | quote }}
  OAUTH2_PROXY_COOKIE_SECRET: {{ .Values.cookie_secret | quote }}