apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gateway-cert
  namespace: {{ .Values.ingress.namespace }}
spec:
  secretName: gateway-cert

  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - aws

  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
  dnsNames:
    - "istio-ingressgateway.{{ .Values.ingress.namespace }}.svc.cluster.local"
  issuerRef:
    name: {{ .Values.cluster_issuer.name }}
    kind: ClusterIssuer
    group: cert-manager.io