# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
    provider "aws" {
      region = "us-east-1"

      default_tags {
        tags = {
            Organization = "Archegos"
            Environment = "Dev"
            Component = "Platform"
            ManagedBy = "Terraform"
            Deployment = "Terragrunt"
        }
      }
    }
