# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "terraform-state-archegos-us-east-1"
    encrypt = false
    key     = "dev/platform/./terraform.tfstate"
    region  = "us-east-1"
  }
}
