# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
    terraform {
      required_version = ">= 1.5.7"

      required_providers {
        aws = {
          source = "hashicorp/aws"
          version = "~> 6.0"
        }

        helm = {
          source = "hashicorp/helm"
          version = "2.17.0"
        }

        kubernetes = {
          source = "hashicorp/kubernetes"
          version = "~> 2.30"
        }

        random = {
          source = "hashicorp/random"
          version = "~> 3.6"
        }
      }
    }
