apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-oidc-client
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
{{- range .Values.staticClients }}
  OIDC_CLIENT_{{ .id | upper | replace "-" "_" }}_ID: {{ .id | quote }}
  OIDC_CLIENT_{{ .id | upper | replace "-" "_" }}_SECRET: {{ .secret | quote }}
{{- end }}