apiVersion: v1
data:
  katib-config.yaml: |
    ---
    apiVersion: config.kubeflow.org/v1beta1
    kind: KatibConfig
    init:
      controller:
        webhookPort: 8443
        trialResources:
          - TrainJob.v1alpha1.trainer.kubeflow.org
          - Job.v1.batch
          - TFJob.v1.kubeflow.org
          - PyTorchJob.v1.kubeflow.org
          - MPIJob.v1.kubeflow.org
          - XGBoostJob.v1.kubeflow.org
    runtime:
      metricsCollectors:
        - kind: StdOut
          image: {{ .Values.image.registry }}/file-metrics-collector:{{ .Values.image.tag }}
        - kind: File
          image: {{ .Values.image.registry }}/file-metrics-collector:{{ .Values.image.tag }}
        - kind: TensorFlowEvent
          image: {{ .Values.image.registry }}/tfevent-metrics-collector:{{ .Values.image.tag }}
          resources:
            limits:
              memory: 1Gi
      suggestions:
        - algorithmName: random
          image: {{ .Values.image.registry }}/suggestion-hyperopt:{{ .Values.image.tag }}
        - algorithmName: tpe
          image: {{ .Values.image.registry }}/suggestion-hyperopt:{{ .Values.image.tag }}
        - algorithmName: grid
          image: {{ .Values.image.registry }}/suggestion-optuna:{{ .Values.image.tag }}
        - algorithmName: hyperband
          image: {{ .Values.image.registry }}/suggestion-hyperband:{{ .Values.image.tag }}
        - algorithmName: bayesianoptimization
          image: {{ .Values.image.registry }}/suggestion-skopt:{{ .Values.image.tag }}
        - algorithmName: cmaes
          image: {{ .Values.image.registry }}/suggestion-goptuna:{{ .Values.image.tag }}
        - algorithmName: sobol
          image: {{ .Values.image.registry }}/suggestion-goptuna:{{ .Values.image.tag }}
        - algorithmName: multivariate-tpe
          image: {{ .Values.image.registry }}/suggestion-optuna:{{ .Values.image.tag }}
        - algorithmName: enas
          image: {{ .Values.image.registry }}/suggestion-enas:{{ .Values.image.tag }}
          resources:
            limits:
              memory: 400Mi
        - algorithmName: darts
          image: {{ .Values.image.registry }}/suggestion-darts:{{ .Values.image.tag }}
        - algorithmName: pbt
          image: {{ .Values.image.registry }}/suggestion-pbt:{{ .Values.image.tag }}
          persistentVolumeClaimSpec:
            accessModes:
              - ReadWriteMany
            resources:
              requests:
                storage: 5Gi
      earlyStoppings:
        - algorithmName: medianstop
          image: {{ .Values.image.registry }}/earlystopping-medianstop:{{ .Values.image.tag }}
kind: ConfigMap
metadata:
  name: katib-config
  namespace: {{ .Values.kubeflow.namespace }}
---
apiVersion: v1
data:
  defaultTrialTemplate.yaml: |-
    apiVersion: batch/v1
    kind: Job
    spec:
      template:
        spec:
          containers:
            - name: training-container
              image: {{ .Values.image.registry }}/pytorch-mnist-cpu:{{ .Values.image.tag }}
              command:
                - "python3"
                - "/opt/pytorch-mnist/mnist.py"
                - "--epochs=1"
                - "--batch-size=16"
                - "--lr=${trialParameters.learningRate}"
                - "--momentum=${trialParameters.momentum}"
          restartPolicy: Never
  enasCPUTemplate: |-
    apiVersion: batch/v1
    kind: Job
    spec:
      template:
        spec:
          containers:
            - name: training-container
              image: {{ .Values.image.registry }}/enas-cnn-cifar10-cpu:{{ .Values.image.tag }}
              command:
                - python3
                - -u
                - RunTrial.py
                - --num_epochs=1
                - "--architecture=\"${trialParameters.neuralNetworkArchitecture}\""
                - "--nn_config=\"${trialParameters.neuralNetworkConfig}\""
          restartPolicy: Never
  pytorchJobTemplate: |-
    apiVersion: kubeflow.org/v1
    kind: PyTorchJob
    spec:
      pytorchReplicaSpecs:
        Master:
          replicas: 1
          restartPolicy: OnFailure
          template:
            spec:
              containers:
                - name: pytorch
                  image: {{ .Values.image.registry }}/pytorch-mnist-cpu:{{ .Values.image.tag }}
                  command:
                    - "python3"
                    - "/opt/pytorch-mnist/mnist.py"
                    - "--epochs=1"
                    - "--lr=${trialParameters.learningRate}"
                    - "--momentum=${trialParameters.momentum}"
        Worker:
          replicas: 2
          restartPolicy: OnFailure
          template:
            spec:
              containers:
                - name: pytorch
                  image: {{ .Values.image.registry }}/pytorch-mnist-cpu:{{ .Values.image.tag }}
                  command:
                    - "python3"
                    - "/opt/pytorch-mnist/mnist.py"
                    - "--epochs=1"
                    - "--lr=${trialParameters.learningRate}"
                    - "--momentum=${trialParameters.momentum}"
kind: ConfigMap
metadata:
  labels:
    katib.kubeflow.org/component: trial-templates
  name: trial-templates
  namespace: {{ .Values.kubeflow.namespace }}
