apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: katib-mysql
  namespace: {{ .Values.kubeflow.namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
