apiVersion: v1
kind: Secret
metadata:
  name: katib-mysql-secrets
  namespace: {{ .Values.kubeflow.namespace }}
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ required "mysql.password is required (set by terraform random_password.katib_mysql_password)" .Values.mysql.password | quote }}
