{{- range $profile := .Values.profiles }}
---
apiVersion: kubeflow.org/v1
kind: Profile
metadata:
  name: {{ $profile.namespace }}
spec:
  owner:
    kind: User
    name: {{ $profile.owner }}
{{- end }}