apiVersion: v1
kind: Service
metadata:
  name: profiles-kfam
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: profile-controller
spec:
  selector:
    app: profile-controller
  ports:
  - name: http-kfam
    port: 8081
    protocol: TCP
    targetPort: 8081