# Monitoring namespace, owned explicitly (was previously created implicitly via Helm
# create_namespace=true). Deliberately OUT OF THE ISTIO AMBIENT MESH: no istio.io/dataplane-mode
# label and no PeerAuthentication. Prometheus scrapes mesh metrics by opening plaintext connections
# to istiod/ztunnel/Envoy metrics ports; bringing these targets behind STRICT mTLS while scraping
# from outside the mesh would make ztunnel silently drop the scrapes. Keeping monitoring out of the
# mesh is the common, lowest-risk posture for a pull-based Prometheus.
#
# MIGRATION (existing clusters only): the namespace already exists (Helm-created, no Terraform
# ownership), so import it once BEFORE the first apply or Terraform will fail trying to create it:
#   terraform import kubernetes_namespace_v1.monitoring monitoring   # or var.prometheus_namespace
# Fresh installs need no import.
resource "kubernetes_namespace_v1" "monitoring" {
  metadata {
    name = var.prometheus_namespace
  }
}

locals {
  app_domain = "grafana.admin.${var.root_domain}"

  # The monitoring stack and its CRDs are two separate Helm releases (CRDs split out so Helm can
  # upgrade them — see helm_release.prometheus_operator_crds). Their schemas must match, so BUMP
  # BOTH TOGETHER on every upgrade. The CRD chart's appVersion is the operator version the stack
  # bundles; verify with `helm search repo prometheus-community/<chart> --versions`.
  #   kube-prometheus-stack 87.2.1  (operator v0.92.0)  <->  prometheus-operator-crds 30.0.0
  kube_prometheus_stack_version    = "87.2.1"
  prometheus_operator_crds_version = "30.0.0"
}

# Prometheus Operator CRDs — managed as a dedicated release so Helm can UPGRADE them on version
# bumps. kube-prometheus-stack ships its CRDs in a `crds/` dir that Helm only installs on a fresh
# install and never updates on upgrade; this chart templates them instead, so the stack sets
# crds.enabled=false and depends on this release. Version is pinned in lockstep via locals above.
#
# MIGRATION (existing clusters only): kube-prometheus-stack previously shipped these CRDs via its
# bundled `crds/` dir, which leaves them with NO Helm ownership metadata. This release refuses to
# adopt them ("invalid ownership metadata; missing key app.kubernetes.io/managed-by") until they
# are labeled/annotated once, BEFORE the first apply:
#   for c in alertmanagerconfigs alertmanagers podmonitors probes prometheusagents prometheuses \
#            prometheusrules scrapeconfigs servicemonitors thanosrulers; do
#     kubectl label    crd $c.monitoring.coreos.com app.kubernetes.io/managed-by=Helm --overwrite
#     kubectl annotate crd $c.monitoring.coreos.com \
#       meta.helm.sh/release-name=prometheus-operator-crds \
#       meta.helm.sh/release-namespace=monitoring --overwrite
#   done
# Fresh installs need none of this (no pre-existing CRDs to adopt).
resource "helm_release" "prometheus_operator_crds" {
  name             = "prometheus-operator-crds"
  description      = "Prometheus Operator CRDs (managed separately so Helm can upgrade them)"
  chart            = "prometheus-operator-crds"
  namespace        = kubernetes_namespace_v1.monitoring.metadata[0].name
  create_namespace = false
  repository       = "https://prometheus-community.github.io/helm-charts"
  version          = local.prometheus_operator_crds_version
}

resource "helm_release" "prometheus" {
  name             = "prometheus"
  description      = "Prometheus monitoring stack"
  chart            = "kube-prometheus-stack"
  namespace        = kubernetes_namespace_v1.monitoring.metadata[0].name
  create_namespace = false
  repository       = "https://prometheus-community.github.io/helm-charts"
  version          = local.kube_prometheus_stack_version

  atomic        = true
  recreate_pods = true

  cleanup_on_fail = true
  values = [
    yamlencode({
      # CRDs are owned by helm_release.prometheus_operator_crds so Helm can upgrade them.
      crds = {
        enabled = false
      }
      alertmanager = {
        enabled = false
      }
      grafana = {
        # Chart-level lint targeting users who paste secrets into committed
        # values.yaml. Our secret is generated by terraform and lives in tfstate
        # alongside every other OIDC client_secret, so this guard adds no
        # exposure delta. Disable so we can pass client_secret inline.
        assertNoLeakedSecrets = false
        # Section keys with dots (e.g. "auth.generic_oauth") become Grafana ini section names.
        "grafana.ini" = {
          server = {
            # Tell Grafana its public URL so it builds correct OIDC redirect URIs.
            root_url = "https://${local.app_domain}"
          }
          auth = {
            disable_login_form = true
            oauth_auto_login   = true
          }
          # Turn off HTTP Basic auth so the built-in admin user can't be used to
          # bypass Dex via API calls. Dex is the only credential path.
          "auth.basic" = {
            enabled = false
          }
          "auth.generic_oauth" = {
            enabled                    = true
            name                       = "Dex"
            client_id                  = "grafana"
            client_secret              = var.grafana_oidc_client_secret
            scopes                     = "openid profile email groups"
            auth_url                   = "${var.dex_issuer_uri}/auth"
            token_url                  = "${var.dex_issuer_uri}/token"
            api_url                    = "${var.dex_issuer_uri}/userinfo"
            allow_sign_up              = true
            allow_assign_grafana_admin = true
            # Single-admin setup: the configured admin email becomes GrafanaAdmin,
            # everyone else lands as Viewer. Refine when more users exist.
            role_attribute_path = "email == '${var.admin_email}' && 'GrafanaAdmin' || 'Viewer'"
          }
        }
      }
    })
  ]

  depends_on = [helm_release.prometheus_operator_crds]
}

# Metrics Service + ServiceMonitor for the AWS LB Controller. Lives here (not in the
# awslb-controller addon) because the addon applies before the Prometheus Operator CRDs exist.
# depends_on the CRD release so monitoring.coreos.com/v1 (ServiceMonitor) is available at apply
# time, and on the stack so it scrapes into a running Prometheus.
resource "helm_release" "lb_controller_monitor" {
  name      = "lb-controller-monitor"
  chart     = "../charts/lb-controller-monitor"
  namespace = var.prometheus_namespace

  depends_on = [helm_release.prometheus_operator_crds, helm_release.prometheus]
}

# Istio mesh observability: ServiceMonitor/PodMonitors that scrape istiod, ztunnel, and Envoy
# gateways/waypoints, plus the upstream Istio Grafana dashboards as ConfigMaps the Grafana sidecar
# auto-loads. depends_on the CRD release so monitoring.coreos.com/v1 (Service/PodMonitor) exists at
# apply time, and on the stack so the dashboard sidecar is running to pick the ConfigMaps up.
resource "helm_release" "istio_monitoring" {
  name      = "istio-monitoring"
  chart     = "../charts/istio-monitoring"
  namespace = kubernetes_namespace_v1.monitoring.metadata[0].name

  depends_on = [helm_release.prometheus_operator_crds, helm_release.prometheus]
}

module "acm" {
  source  = "terraform-aws-modules/acm/aws"
  version = "~> 6.0"

  domain_name = local.app_domain
  zone_id     = var.root_zone_id

  validation_method = "DNS"
}

resource "kubernetes_ingress_v1" "grafana_ingress" {
  metadata {
    name      = "grafana-ingress"
    namespace = var.prometheus_namespace
    annotations = {
      "external-dns.alpha.kubernetes.io/hostname"      = local.app_domain
      "kubernetes.io/ingress.class"                    = "alb"
      "alb.ingress.kubernetes.io/healthcheck-path"     = "/api/health"
      "alb.ingress.kubernetes.io/success-codes"        = "200"
      "alb.ingress.kubernetes.io/group.name"           = "${var.resource_prefix}-alb"
      "alb.ingress.kubernetes.io/target-type"          = "ip"
      "alb.ingress.kubernetes.io/scheme"               = "internet-facing"
      "alb.ingress.kubernetes.io/listen-ports"         = jsonencode([{ "HTTP" : 80 }, { "HTTPS" : 443 }])
      "alb.ingress.kubernetes.io/actions.ssl-redirect" = jsonencode({ "Type" : "redirect", "RedirectConfig" : { "Protocol" : "HTTPS", "Port" : "443", "StatusCode" : "HTTP_301" } })
      "alb.ingress.kubernetes.io/inbound-cidrs"        = "0.0.0.0/0"
      # No need to declare certificate: https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/ingress/cert_discovery/
    }
  }

  spec {
    ingress_class_name = "alb"

    tls {
      hosts = [local.app_domain]
    }

    // taken from https://www.stacksimplify.com/aws-eks/aws-alb-ingress/learn-to-enable-ssl-redirect-in-alb-ingress-service-on-aws-eks/
    rule {
      host = local.app_domain

      http {
        path {
          path      = "/"
          path_type = "Prefix"

          backend {
            service {
              name = "ssl-redirect"

              port {
                name = "use-annotation"
              }
            }
          }
        }
      }
    }

    rule {
      host = local.app_domain

      http {
        path {
          path      = "/"
          path_type = "Prefix"

          backend {
            service {
              name = "prometheus-grafana"

              port {
                # Grafana uses port 3000 by default. We reference the service port name here.
                name = "http-web"
              }
            }
          }
        }
      }
    }
  }

  wait_for_load_balancer = true

  depends_on = [module.acm, helm_release.prometheus]
}
