apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim-v2
  namespace: {{ .Values.kubeflow.namespace }}
  labels:
    application-crd-id: kubeflow-pipelines
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: {{ .Values.kubeflow.namespace }}
  labels:
    application-crd-id: kubeflow-pipelines
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi