apiVersion: v2
appVersion: 2.16.1
description: A Helm chart for Kubeflow pipelines
name: kubeflow-pipelines
type: application
<<<<<<< Updated upstream
version: 1.1.8
=======
<<<<<<< Updated upstream
version: 1.1.7
=======
version: 1.1.9
>>>>>>> Stashed changes
>>>>>>> Stashed changes
