apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-registry-deployment
  namespace: {{ .Values.namespace }}
  labels:
    component: model-registry-server
spec:
  replicas: 1
  selector:
    matchLabels:
      component: model-registry-server
  template:
    metadata:
      labels:
        component: model-registry-server
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        runAsNonRoot: true
      containers:
        - name: rest-container
          image: {{ .Values.registry.image }}:{{ .Values.registry.tag }}
          command:
            - /model-registry
            - proxy
          args:
            - --hostname=0.0.0.0
            - --port=$(MODEL_REGISTRY_REST_SERVICE_PORT)
            - --datastore-type=$(MODEL_REGISTRY_DATA_STORE_TYPE)
            - --embedmd-database-dsn=$(MYSQL_USER_NAME):$(MYSQL_ROOT_PASSWORD)@tcp(model-registry-db:$(MYSQL_PORT))/$(MYSQL_DATABASE)?charset=utf8mb4
          envFrom:
            - configMapRef:
                name: model-registry-configmap
            - secretRef:
                name: model-registry-db-secrets
            - configMapRef:
                name: model-registry-db-parameters
          ports:
            - name: http-api
              containerPort: 8080
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 10
            httpGet:
              path: /readyz/isDirty
              port: http-api
            timeoutSeconds: 5
            failureThreshold: 3
          startupProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              path: /readyz/isDirty
              port: http-api
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            httpGet:
              path: /readyz/health
              port: http-api
            timeoutSeconds: 5
            failureThreshold: 3
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
      serviceAccountName: model-registry-server
