apiVersion: v1
kind: ConfigMap
metadata:
  name: model-registry-configmap
  namespace: {{ .Values.namespace }}
  labels:
    component: model-registry-server
data:
  MODEL_REGISTRY_REST_SERVICE_HOST: "model-registry-service"
  MODEL_REGISTRY_REST_SERVICE_PORT: "8080"
  MODEL_REGISTRY_DATA_STORE_TYPE: "embedmd"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: model-registry-db-parameters
  namespace: {{ .Values.namespace }}
  labels:
    component: model-registry-server
data:
  MYSQL_DATABASE: {{ .Values.registry.db.database | quote }}
  MYSQL_PORT: {{ .Values.registry.db.port | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: model-registry-db-secrets
  namespace: {{ .Values.namespace }}
  labels:
    component: model-registry-server
type: Opaque
stringData:
  MYSQL_USER_NAME: {{ .Values.registry.db.user | quote }}
  MYSQL_ROOT_PASSWORD: {{ required "registry.db.password is required" .Values.registry.db.password | quote }}