apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-registry-mysql
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.registry.db.storage }}
