{{- if .Values.catalog.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: model-catalog-postgres
  namespace: {{ .Values.namespace }}
  labels:
    component: model-catalog-server
spec:
  serviceName: model-catalog-postgres
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres
      app.kubernetes.io/part-of: model-catalog
  replicas: 1
  template:
    metadata:
      name: postgres
      labels:
        app.kubernetes.io/name: postgres
        app.kubernetes.io/part-of: model-catalog
        app.kubernetes.io/component: database
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        runAsNonRoot: true
        fsGroup: 70
      containers:
      - name: postgres
        image: {{ .Values.catalog.postgres.image }}:{{ .Values.catalog.postgres.tag }}
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        envFrom:
        - secretRef:
            name: model-catalog-postgres
        ports:
        - name: postgres
          containerPort: 5432
        volumeMounts:
        - name: model-catalog-postgres
          mountPath: /var/lib/postgresql/data
        securityContext:
          runAsUser: 70
          runAsGroup: 70
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
      volumes:
      - name: model-catalog-postgres
        persistentVolumeClaim:
          claimName: model-catalog-postgres
---
apiVersion: v1
kind: Service
metadata:
  name: model-catalog-postgres
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: model-catalog
    app.kubernetes.io/part-of: model-catalog
    app.kubernetes.io/component: database
spec:
  selector:
    app.kubernetes.io/part-of: model-catalog
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
  type: ClusterIP
  ports:
  - port: 5432
    protocol: TCP
    name: postgres
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-catalog-postgres
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.catalog.postgres.storage }}
{{- end }}
