apiVersion: v1
kind: Service
metadata:
  name: jupyter-web-app-service
  namespace: {{ .Values.namespace }}
  labels:
    app: jupyter-web-app
    kustomize.component: jupyter-web-app
    run: jupyter-web-app
spec:
  type: ClusterIP
  selector:
    app: jupyter-web-app
    kustomize.component: jupyter-web-app
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5000