apiVersion: v1
kind: ConfigMap
metadata:
  name: jupyter-web-app-config
  namespace: {{ .Values.namespace }}
  labels:
    app: jupyter-web-app
    kustomize.component: jupyter-web-app
data:
  spawner_ui_config.yaml: |
{{ .Files.Get "files/spawner_ui_config.yaml" | indent 4 }}