apiVersion: apps/v1
kind: Deployment
metadata:
  name: notebook-controller-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: notebook-controller
    kustomize.component: notebook-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notebook-controller
      kustomize.component: notebook-controller
  template:
    metadata:
      labels:
        app: notebook-controller
        kustomize.component: notebook-controller
    spec:
      serviceAccountName: notebook-controller-service-account
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: manager
        image: {{ .Values.notebook_controller.image }}:{{ .Values.notebook_controller.tag }}
        command:
        - /manager
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: notebook-controller-config
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          runAsUser: 1000
          capabilities:
            drop:
            - ALL