name: Infra - Destroy
run-name: ${{ github.actor}} is DESTROYING DEV! 🔥

on:
  workflow_dispatch: # enables manual execution
    inputs:
      infra_env:
        description: 'Environment to destroy'
        required: true
        default: 'dev'
        type: choice
        options:
            - 'dev'
      region:
        description: 'Region to destroy'
        required: true
        default: 'us-east-1'
        type: choice
        options:
            - 'us-east-1'

concurrency: # set other jobs with the same 'group' in a queue
  group: infra-deploy
  cancel-in-progress: false

permissions:
  id-token: write      # allow creation of openid connect token
  contents: read       # allow read repository's content by steps
  pull-requests: write # allow adding comments in a pull request

env:
  tf_version: '1.9.8'
  tg_version: '0.68.6'
  working_dir: '.'

jobs:
  destroy:
    name: Infra - Destroy
    runs-on: ubuntu-latest
    timeout-minutes: 30 # Avoid using GitHub Runners time
    defaults:
      run:
        shell: bash

    environment: ${{ inputs.infra_env }}

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          aws-region: ${{ inputs.region }}
          role-session-name: github-actions-oidc-session
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}

      - name: Destory
        id: destroy
        uses: gruntwork-io/terragrunt-action@cf355638dbd066b6a70eb01f31ad9293870a0e34 # v2.1.4
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: ${{ env.working_dir }}
          tg_command: |
            run-all destroy
              --terragrunt-non-interactive 
              --terragrunt-no-color
              --terragrunt-exclude-dir flux/base
              --terragrunt-exclude-dir flux/terraform-controller
        env:
          DEPLOYMENT:  archegos-${{ inputs.infra_env }}-${{ inputs.region }}
